name: Deploy Rails application to NeymarSabin's MACBOOK

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: install deployment deps
        run: |
          apt install -y libsqlite3-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.1"
          bundler-cache: true

      - name: Run good old capistrano magick
        run: |
          mkdir -p ~/.ssh && echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
          bundle exec cap production deploy:check
