name: Deploy Rails application to NeymarSabin's MACBOOK

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.1"
          bundler-cache: true

      - name: Run good old capistrano magick
        run: |
          bundle exec cap production deploy:check
